name: Release

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --local user.email "79938743+Pianonic@users.noreply.github.com"
          git config --local user.name "PianoNic"

      - name: Get version from release
        id: get_version
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          VERSION=${VERSION#v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Release version: $VERSION"

      - name: Update application.properties
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          echo "Updating version to: $VERSION"
          
          if [ -f application.properties ]; then
            sed -i "s/^APP_VERSION=.*/APP_VERSION=$VERSION/" application.properties
            sed -i "s/^APP_ENVIRONMENT=.*/APP_ENVIRONMENT=production/" application.properties
          else
            echo "APP_VERSION=$VERSION" > application.properties
            echo "APP_ENVIRONMENT=production" >> application.properties
          fi
          
          echo "Updated application.properties:"
          cat application.properties

      - name: Commit version update
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          git add application.properties
          git commit -m "🚀 Release version $VERSION [skip ci]"
          git push origin HEAD:main

  build-and-push-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable=${{ !github.event.release.prerelease }}

      - name: Build and push Multi-Arch Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max